# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
 
- script: |
    docker run --user $(id -u) --rm -v $(pwd):/dastardly -e DASTARDLY_TARGET_URL=https://ginandjuice.shop -e DASTARDLY_OUTPUT_FILE=/dastardly/dastardly-report.xml public.ecr.aws/portswigger/dastardly:latest
   
  displayName: 'Dastardly scan'
 
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: |
      **/TEST-*.xml
      dastardly-report.xml
    failTaskOnFailedTests: true